### ISSUE TITLE
Requesting Glyph Music Visulization support

### ISSUE THREAD

**Issue by PiyushSingh3** [MissingCore/Music#105]
### What device did this occur on?

Phone (2a)

### What version of Android is your device running?

14

### App Version

1.0.3

### Glyph Music Visualization Support

Glyph Music Visualization is currently not working. It would be helpful to have a default option to enable or disable this feature directly within the app.

The current implementation is not very intuitive, as the Glyph lights are triggered by any sound source, including YouTube videos, which can be distracting.

**Comment by cyanChill** [comment]
So this is 2 different issues:

1. **Glyph Music Visualization Not Working in the App:** I'm aware of this, this should be fixed in the next major release.
2. **Glyph Music Visualization "Activation" Behavior:** This is something I can't control as it's part of Nothing OS (ie: there's no way to have an enable/disable option for the feature within this app, you have to either use the "Glyphs" button in the control panel to enable/disable glyphs or disable the "Glyph Music Visualization" feature in the Android settings).
