### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by xmdnx** [MissingCore/Music#114]
Logs: https://bin.mkr.pw/~674fde7f632ce757b6266aba

**Comment by cyanChill** [comment]
I think I might have an idea of what's causing the issue, though this might be hard to tell since I don't have a physical device where this issue occurs. I'm guessing the issue is due to trying to return the path of a specific directory that doesn't exist.
- In the metadata package, we export a variable containing the path of the music directory - if the music directory doesn't exist (which might happen due to this case), an error will be thrown as we tried to get the path of something that doesn't exist.

I'm going to assume that this might have happened on a Huawei, Redmi, or Realme device as these are the devices where things randomly break.

This will probably land in the next **major** version since I'm probably (optimally) 80% done.

**Comment by cyanChill** [comment]
If you're still interested in this app, can you test [`v2.0.0-rc.1`](https://github.com/MissingCore/Music/releases/tag/v2.0.0-rc.1) to see if this is still an issue?

**Comment by xmdnx** [comment]
yea, that worked!
