### ISSUE TITLE
I am not able to access music

### ISSUE THREAD

**Issue by adarshtr0011** [MissingCore/Music#45]
All my songs are in music folder, still can't acces any songs
Using NP2
They are in m4a format btw

**Comment by cyanChill** [comment]
Currently, we only support `.mp3` & `.flac` (even though the package I made added support for `.m4a`/`.mp4`). This is because I know of someone using this app who has ~15k tracks, most which are `.mp4` (for AAC), and since the saving logic isn't as performant as it should be, it would take a pretty long time to save all of their tracks.

I'm currently working on a different package that uses Android's built in metadata reader (I don't know Kotlin, so it's going take a bit of time), which drastically cut down the saving time (and also supports more formats), but its probably not enough. In addition to this new package, I'm probably going change the process of how we save tracks - ie: just save tracks as "tagless" first, then populate them with metadata in the background. Although the `ARTISTS` & `ALBUMS` tab will be pretty useless at first, the `FOLDERS` tab should supplement the behavior for now.
- With this, I'll probably display a modal for first-time users explaining this behavior as it wasn't clear before (unless you read the README on this repository) for how we save images for the tracks.

This is what I have planned to come out in `v1.0.0-rc.11`.

**Comment by cyanChill** [comment]
@adarshtr0011 `v1.0.0-rc.11` has been released, which changes the method of obtaining metadata for tracks (now using an Android API instead of manual logic). This should now detect the metadata of `.m4a` files.

In addition, we added an allowlist/blocklist feature in case your music isn't all in the `Music` directory on your device.
