### ISSUE TITLE
It is best to avoid using Ndot in important parts of the UI.

### ISSUE THREAD

**Issue by reindex-ot** [MissingCore/Music#63]
There are many places where you should refrain from using Ndot. Ndot does not support anything other than alphanumeric characters. Ndot JP Extended can be used to support other languages, but this is not recommended.

![Screenshot_2024-08-10-09-38-02-405_com cyanchill missingcore music](https://github.com/user-attachments/assets/f14dfefd-3b36-4076-b6dd-3d3d8851d143)

**Comment by reindex-ot** [comment]
Ndot JP Extended font.
Not recommended for use in UI overall.

![NdotJP](https://github.com/user-attachments/assets/6c44dcc9-48cb-49ac-91e2-fbb2d8afc20e)

**Comment by cyanChill** [comment]
According to Google, if a font doesn't support a certain typeface (ie: Japanese), it'll fallback to [`Noto`](https://fonts.google.com/knowledge/using_type/language_support_in_fonts). I'll probably switch the font used in the heading & subheading in the modals to Geist Mono as it'll blend in better with Noto.

It'll look something like the below.
- Geist Mono Light / Noto Sans JP DemiLight
- Geist Mono Regular / Noto Sans JP Regular

![image](https://github.com/user-attachments/assets/e12cdc19-a5fc-4e1d-9065-c39afeee91e5)

**Comment by reindex-ot** [comment]
I'd like the option to fallback some fonts in the UI from Ndot to NotoSans.

**Comment by cyanChill** [comment]
It should already do that by default — in the original behavior, the font weight of Noto Sans is bolded due to ndot not following the standard font weights (ie: no "Regular", "Light", "Bold" weights), so I think it just defaults to "Bold".

I've switched the modals to use Geist Mono from Ndot in 9b2c97e; probably might convert the rest when adding i18n.

Probably won't use the Ndot JP Extended font since we'll probably end up in this scenario where the current font doesn't support this language and we'll get some weird font contrast.

**Comment by reindex-ot** [comment]
okay.
